version: '3.1'

services:

  jenkins:
    image: jenkins:latest
    environment:
      - MAVEN_OPTS=-Xmx512m
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins-home:/var/jenkins_home
    deploy:
      placement:
        constraints: [node.role == manager]

  selenium:
    image: selenium/standalone-chrome:3.11.0-dysprosium
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8081:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  jenkins-home: